application: dbow-site
version: 7
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: latest

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /bower_components
  static_dir: bower_components

- url: /animation
  static_dir: animation

- url: /fonts
  static_dir: fonts
  
- url: /img
  static_dir: img

- url: .*
  script: main.py
